---
layout: post
title: Mguid tool
category: Tools
tags: [Tools]
---

_Eudoxys Sciences releases `mguid` developer tool to create and manage magic GUIDs_.

A magic GUID is a GUID that embeds an encoding related to the source of the GUID. Magic GUIDs can be used to determine whether two GUIDs were generated in the same context. That can be useful for applications that need to check whether a GUID is exogenous, i.e., was the GUID created by another application. It can also be used by a third application to determine whether two GUIDs were generated by two different applications or by the same application.

Magic GUIDs contain a pattern that is uniquely identifiable if the magic number is known. The `--random` option generates a Version 4 GUID using a random magic number. If you know the magic number you can verify that a GUID was generated with the magic number by using the `--check` option. If an app has two GUIDs, they can verify that they were generated using the same magic number using the `--same` option. 

The `mguid` module can also be called from another Python module using the `main()` function or from the command line of a shell. The command line options are also available as python functions in the module.

For more information on the `mguid` tool, see the **[mguid documentation page](https://www.eudoxys.com/mguid)** or download it from the **[mguid repository on github](https://github.com/eudoxys/mguid)**.
